export const initialMedicines = [
  { 
    id: 1, 
    name: 'Cảm mạo thông', 
    generic: 'Dược liệu', 
    category: 'Thuốc giải biểu', 
    isHeader: false,
    indications: 'Trị cảm cúm, viêm xoang, viêm mũi dị ứng với biểu hiện: Sốt, đau đầu, hắt hơi, sổ mũi, chảy nước mũi, nghẹt mũi.',
    contraindications: 'Mẫn cảm với bất kỳ thành phần nào của thuốc. Phụ nữ có thai. Trĩ, sa dạ dày, sa dạ con...',
    icd_codes: 'J00; J01; J10; J30',
    dosage: '1. Người lớn: 2 viên x 2-3 lần/ ngày.\n2. Trẻ em trên 5 tuổi: 1 viên x 2-3 lần/ ngày.',
    notes: '',
    stock: 1200,
    status: 'active',
    images: ['https://picsum.photos/seed/med1/400/300']
  },
  { 
    id: 2, 
    name: 'Nhóm thuốc thanh nhiệt, giải độc, tiêu ban, lợi thủy', 
    isHeader: true,
    category: 'Thanh nhiệt'
  },
  { 
    id: 3, 
    name: 'Kim ngân hoa', 
    generic: 'Lonicera japonica', 
    category: 'Thanh nhiệt', 
    isHeader: false,
    indications: 'Thanh nhiệt, giải độc, tán độc, dùng trị mụn nhọt, ban sởi, mày đay, lở ngứa.',
    contraindications: 'Người tỳ vị hư hàn.',
    icd_codes: 'L20; L21; L23',
    dosage: 'Ngày dùng 12-16g dạng thuốc sắc hoặc hãm.',
    notes: 'Cần chú ý khi dùng cho trẻ nhỏ.',
    stock: 500,
    status: 'active',
    images: ['https://picsum.photos/seed/med3/400/300']
  },
  { 
    id: 4, 
    name: 'Paracetamol', 
    generic: 'Acetaminophen', 
    category: 'Thuốc giảm đau, hạ sốt', 
    isHeader: false,
    indications: 'Giảm đau nhẹ đến vừa, hạ sốt.',
    contraindications: 'Người bệnh nhiều lần thiếu máu hoặc có bệnh tim, phổi, thận hoặc gan. Quá mẫn với paracetamol.',
    icd_codes: 'R50; R52',
    dosage: 'Người lớn: 500-1000mg mỗi 4-6 giờ, tối đa 4g/ngày.\nTrẻ em: 10-15mg/kg mỗi 4-6 giờ.',
    notes: 'Không dùng cùng các thuốc khác có chứa paracetamol để tránh quá liều.',
    stock: 5000,
    status: 'active',
    images: ['https://picsum.photos/seed/med4/400/300']
  },
  { 
    id: 5, 
    name: 'Amoxicillin', 
    generic: 'Amoxicillin', 
    category: 'Kháng sinh', 
    isHeader: false,
    indications: 'Nhiễm khuẩn đường hô hấp trên và dưới, nhiễm khuẩn đường tiết niệu, nhiễm khuẩn da và mô mềm.',
    contraindications: 'Người bệnh có tiền sử dị ứng với các loại penicillin.',
    icd_codes: 'J01; J02; J03; J04; N39.0',
    dosage: 'Người lớn: 250-500mg mỗi 8 giờ.\nTrẻ em: 20-40mg/kg/ngày chia làm 3 lần.',
    notes: 'Cần uống đủ liều và thời gian theo chỉ định của bác sĩ.',
    stock: 2000,
    status: 'active',
    images: ['https://picsum.photos/seed/med5/400/300']
  },
  { 
    id: 6, 
    name: 'Omeprazole', 
    generic: 'Omeprazole', 
    category: 'Thuốc dạ dày', 
    isHeader: false,
    indications: 'Trào ngược dạ dày thực quản (GERD), loét dạ dày tá tràng, hội chứng Zollinger-Ellison.',
    contraindications: 'Quá mẫn với omeprazole, esomeprazole, hoặc các dẫn xuất benzimidazole khác.',
    icd_codes: 'K21; K25; K26',
    dosage: 'Người lớn: 20-40mg/ngày, uống trước bữa ăn sáng.',
    notes: 'Nên nuốt nguyên viên, không nhai hoặc nghiền nát.',
    stock: 1500,
    status: 'active',
    images: ['https://picsum.photos/seed/med6/400/300']
  },
  { 
    id: 7, 
    name: 'Boganic', 
    generic: 'Cao Actiso, Cao Rau đắng đất, Cao Bìm bìm', 
    category: 'Thanh nhiệt', 
    isHeader: false,
    indications: 'Suy giảm chức năng gan, viêm gan, xơ gan, vàng da, dị ứng, mụn nhọt, lở ngứa.',
    contraindications: 'Người mẫn cảm với bất kỳ thành phần nào của thuốc. Người bị viêm tắc mật.',
    icd_codes: 'K71; K73; K74',
    dosage: 'Người lớn: 1-2 viên/lần x 3 lần/ngày.\nTrẻ em trên 8 tuổi: 1 viên/lần x 2-3 lần/ngày.',
    notes: 'Có thể dùng dài ngày để bảo vệ gan.',
    stock: 3000,
    status: 'active',
    images: ['https://picsum.photos/seed/med7/400/300']
  },
  { 
    id: 8, 
    name: 'Hoạt huyết dưỡng não', 
    generic: 'Cao Đinh lăng, Cao Bạch quả', 
    category: 'Hoạt huyết', 
    isHeader: false,
    indications: 'Suy giảm trí nhớ, căng thẳng thần kinh, kém tập trung. Thiểu năng tuần hoàn não, hội chứng tiền đình.',
    contraindications: 'Phụ nữ có thai, người đang chảy máu, người rối loạn đông máu.',
    icd_codes: 'G45; F06.7',
    dosage: 'Người lớn: 2-3 viên/lần x 2-3 lần/ngày.\nTrẻ em: 1 viên/lần x 2-3 lần/ngày.',
    notes: 'Uống sau bữa ăn.',
    stock: 2500,
    status: 'active',
    images: ['https://picsum.photos/seed/med8/400/300']
  }
];

export const initialCategories = [
  { id: 1, name: 'Thuốc giải biểu', count: 45, description: 'Các thuốc điều trị triệu chứng cảm mạo, phong hàn, giúp cơ thể giải độc qua đường mồ hôi.', color: 'bg-blue-500' },
  { id: 2, name: 'Thanh nhiệt', count: 120, description: 'Nhóm thuốc giúp hạ sốt, giải độc gan, tiêu ban và hỗ trợ điều trị các chứng viêm nhiễm nhiệt độc.', color: 'bg-emerald-500' },
  { id: 3, name: 'Trừ phong thấp', count: 85, description: 'Chuyên biệt cho các bệnh lý xương khớp, phong thấp, đau nhức vai gáy và thần kinh tọa.', color: 'bg-amber-500' },
  { id: 4, name: 'Hành khí', count: 32, description: 'Điều trị các chứng khí trệ, đầy bụng, khó tiêu và hỗ trợ lưu thông khí huyết.', color: 'bg-purple-500' },
  { id: 5, name: 'Hoạt huyết', count: 64, description: 'Điều trị các chứng huyết ứ, đau nhức do chấn thương và hỗ trợ tuần hoàn máu.', color: 'bg-red-500' },
  { id: 6, name: 'An thần', count: 28, description: 'Hỗ trợ điều trị mất ngủ, suy nhược thần kinh, giúp ổn định tâm lý và cải thiện chất lượng giấc ngủ.', color: 'bg-indigo-500' },
  { id: 7, name: 'Thuốc giảm đau, hạ sốt', count: 150, description: 'Các loại thuốc giúp giảm đau, hạ sốt nhanh chóng và an toàn.', color: 'bg-orange-500' },
  { id: 8, name: 'Kháng sinh', count: 200, description: 'Thuốc điều trị các bệnh nhiễm khuẩn do vi khuẩn gây ra.', color: 'bg-teal-500' },
  { id: 9, name: 'Thuốc dạ dày', count: 75, description: 'Điều trị các bệnh lý về dạ dày, tá tràng, trào ngược.', color: 'bg-yellow-500' },
];
